# Generated by Django 4.1 on 2022-08-09 22:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='NovoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_professor', models.IntegerField(verbose_name='Id do professor')),
                ('professor_responsavel', models.CharField(max_length=150, verbose_name='Professor responsável')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('carga_horaria', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(350)], verbose_name='Carga horároia')),
                ('ementa', models.CharField(max_length=250, verbose_name='Ementa')),
                ('obj_geral', models.TextField(max_length=250, verbose_name='Objetivo geral')),
                ('status', models.TextField(choices=[('AGUARDANDO_AVALIACAO', 'Aguardando avaliação'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default=0, verbose_name='Status')),
                ('area_tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.areatematica', verbose_name='Áreas temáticas')),
            ],
            options={
                'verbose_name_plural': 'Planos de curso',
            },
        ),
        migrations.CreateModel(
            name='NovoTopidoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('plano_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to='cursos.novoplano')),
            ],
            options={
                'verbose_name': 'Tópicos de aula',
            },
        ),
    ]
